### PR TITLE
Basic stuff

### PR DESCRIPTION
**Pull request by mcollina**
Related https://github.com/pinojs/pino/issues/117

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
LGTM 👍

**Comment by davidmarkclements** [comment]
We also have an extended community/ecosystem (e.g. https://www.npmjs.com/package/pino-mongodb) - should we add that stuff? 

I think this is ok, but I think this repo should be more about the process on getting involved with pino, how to add your module as an official module, how to get help building your third party module

stuff like that?

From that perspective I'm not sure this closes pinojs/pino#117

**Comment by jsumners** [comment]
Hmm, maybe it doesn't close that issue, but the title "Basic stuff" certainly encompasses the content of the PR.

**Comment by davidmarkclements** [comment]
yah agreed

**Pull request merged**
